# Generated by Django 2.2.11 on 2020-03-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0002_auto_20200328_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
