# Generated by Django 2.2.11 on 2020-04-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0004_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
