# Generated by Django 2.2.11 on 2020-04-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0005_auto_20200425_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(default='null', upload_to='collection/%Y/%m/%d'),
        ),
    ]
